---
  - name: Configure Profile for non ec2
    block:
      - name: Set Default Profile
        template:
          src: "{{ aws_cw_agent_profile_template }}"
          dest: "{{ aws_cw_agent_profile_path }}/credentials"
        tags:
          - profile
      - name: Set Default Config for Profile
        template:
          src: "{{ item }}"
          dest: "{{ aws_cw_conf }}/common-config.toml"
        with_first_found:
          - files:
              - "{{ aws_cw_agent_common_template }}"
        tags:
          - config
    when: aws_cw_agent_type !='ec2'

  - name: Configure Nix Agent
    block:
      - name: deploy agent configuration
        template:
          src: "{{ item }}"
          dest: "{{ aws_cw_root }}/amazon-cloudwatch-agent.json"
          mode: 0644
        with_first_found:
          - files:
              - "{{ aws_cw_config_template_path }}"
        tags:
          - config
        register: config

      - name: start cloudwatch agent
        command: |
          ./amazon-cloudwatch-agent-ctl \
              -a fetch-config \
              -m {{ aws_cw_agent_type }} \
              -c file:{{ aws_cw_root }}/amazon-cloudwatch-agent.json \
              -s
        args:
          chdir: "{{ aws_cw_root }}/bin"
        when: config is changed
    when: ansible_os_family != "Windows"

  - name: Configure Windows Agent
    block:
      - name: deploy windows agent configuration
        template:
          src: "{{ item }}"
          dest: "{{ aws_cw_root }}/amazon-cloudwatch-agent.json"
        with_first_found:
          - files:
              - "{{ aws_cw_config_template_path }}"
        tags:
          - config
        register: config

      - name: start windows cloudwatch agent
        win_command: |
          powershell.exe ./amazon-cloudwatch-agent-ctl.ps1 \
              -a fetch-config \
              -m {{ aws_cw_agent_type }} \
              -c file:'{{ aws_cw_root }}/amazon-cloudwatch-agent.json' \
              -s
        args:
          chdir: "{{ aws_cw_root }}"
        when: config is changed
    when: ansible_os_family == "Windows"